### PR TITLE
Add IRC2Mintable

### PR DESCRIPTION
**Pull request by ICONationDevTeam**
IRC2Mintable is able to mint new tokens at any time. 
The minting is only callable by the contract operator.

### CODE REVIEW

**Comment by ICONationDevTeam** [comment]
There's an issue I'm not sure how to handle it properly :

```java
minter.set(Context.getOwner());
```

The minter role is reset to owner after a SCORE update, as the contructor is called after an update.

How to properly detect an update in order to avoid override the minter role in that case ?

**Comment by sink772** [comment]
Thanks for your contribution.
I see couple of minor things need to be fixed, but i will fix them after merging your PR first.

**Comment by sink772** [comment]
> There's an issue I'm not sure how to handle it properly :
> 
> ```java
> minter.set(Context.getOwner());
> ```
> 
> The minter role is reset to owner after a SCORE owner, as the contructor is called after an update.
> 
> How to properly detect an update in order to avoid override the minter role in that case ?

In case of update, the `minter` state already has a certain value, thus you can check the value before executing the above line.

**Comment by ICONationDevTeam** [comment]
Right thanks! I'll look at your changes carefully for learning.

What's the correct way to detect if a varDB/dictDb/arrayDB already has a value please?

```java
minter.set(minter.getOrDefault(Context.getOwner()));
```

Should be correct ?

**Comment by sink772** [comment]
Ah... I didn't know that you asked me another question.
Yes, your snippet works fine, but I think you don't need to set again if the minter has a certain value.
```
if (minter.get() == null) {
    minter.set(Context.getOwner());
}
```

**Pull request merged**
